global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "patient-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:7001"]
        labels:
          application: "Patient Service"
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100", "172.18.128.1:9182"]
  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8889"]
      - targets: ["otel-collector:8888"]            